CREATE TABLE usuario(
    user VARCHAR(50) PRIMARY KEY,
    nombres VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    code VARCHAR(5) NOT NULL,
    celular VARCHAR(50) NOT NULL,
    ci VARCHAR(15) NOT NULL,
    exp VARCHAR(3) NOT NULL,
    rol VARCHAR(15) NOT NULL,
    autorizacion INT(2) NOT NULL,
    img VARCHAR(500) DEFAULT '',
    estado INT NOT NULL DEFAULT 1,
    fec_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR(50) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (ci)
);

CREATE TABLE auth(
    user VARCHAR(50) PRIMARY KEY,
    password VARCHAR(500) NOT NULL,
    pregunta VARCHAR(100) NOT NULL,
    respuesta VARCHAR(100) NOT NULL,
    FOREIGN KEY (user) REFERENCES usuario(user) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE code(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    code VARCHAR(4) NOT NULL,
    type VARCHAR(50),
    descripcion VARCHAR(500) NOT NULL,
    estado INT NOT NULL DEFAULT 1
);